added rate limiter to login api      issue #159
Yashgabani845/hiring-portal pull request #162
Opened 2024-10-15 15:23 UTC by AyushSharma72

i added rate limit to login api so that only a certain number of request will be processed by the login api

it will:
prevent bots attack
reduce the load to the website

ss:
login with wrong password:
![Screenshot (252)](https://github.com/user-attachments/assets/96174c14-00a3-4017-bc65-7228ca308ff1)

after 5 times the login api will not process request form the same ip address for 5 minutes
![Screenshot (251)](https://github.com/user-attachments/assets/9d7105bc-945a-413e-b314-7c8f97314e31)

i have tested this with postman

please add gssoc-ext and level2 label before merge

2024-10-16 05:37 UTC, Yashgabani845 requested changes
resolve the merge conflicts

2024-10-16 06:23 UTC, AyushSharma72 commented
> resolve the merge conflicts

Check now @Yashgabani845

2024-10-16 16:29 UTC, Yashgabani845 approved these changes

2024-10-23 14:25 UTC, AyushSharma72 commented
> > resolve the merge conflicts
> 
> Check now @Yashgabani845

hey @Yashgabani845  please merge this pr

2024-10-24 05:59 UTC, Yashgabani845 approved these changes

2024-10-24 05:59 UTC, merged